name: Sincronizar Ponteiros dos Submódulos

on:
  repository_dispatch:
    types: [update_submodule]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código Privado
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          ref: devlab
          submodules: true

      - name: Atualizar Todos os Submódulos
        run: |
          git config --global user.name "Github Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Atualizar todos os submódulos para os últimos commits das suas branches
          git submodule update --remote --merge
          
          # Registrar as mudanças no repositório pai
          git add packages/ui packages/sdk packages/utils
          git diff-index --quiet HEAD || (git commit -m "chore: atualizar ponteiros dos submódulos [auto]" && git push origin devlab)
